//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caseABC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcel
    {
        public int parcelId { get; set; }
        public int customerId { get; set; }
        public string pickupAddress { get; set; }
        public System.DateTime pickupDate { get; set; }
    }
}
