//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caseABC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int TrackingId { get; set; }
        public System.DateTime TrackingDate { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public int parcelId { get; set; }
    
        public virtual Parcel Parcel { get; set; }
    }
}
